### ISSUE TITLE
[bug] Redstone signal between sides?

### ISSUE THREAD

**Issue by Pentasis** [dannydjdk/Tiny-Redstone#115] opened 2022-12-14 10:18 UTC
MC 1.19.2
Forge 43.2.0
Tiny rs 4.1.0
Tiny gates 3.0.0

Not sure if this is a bug or which mod (gates/redstone) does this. Please look at screenshots for explanation.
First screenshot shows the wireless transmitter from Create is OFF, but as soon as I add the tine-redstone dust to the lower-left of the panel it turns ON, while it it on a different side?
Is this a bug or am I doing something stupud?
![ss1](https://user-images.githubusercontent.com/7046024/207568904-9f38a59c-e023-4571-9423-2a17c49b008f.png)
![ss2](https://user-images.githubusercontent.com/7046024/207568932-e36aab56-7f97-446b-b462-f123a90f2674.png)

**Comment by dannydjdk** [comment] 2022-12-14 16:03
This definitely looks like a bug. Thanks for the report!

**Comment by dannydjdk** [comment] 2022-12-14 23:15
This is almost certainly a bug with Create's Redstone Link. The specific issue is that when a block outputs redstone to the bottom, the Redstone Link picks up the signal no matter which side of the block it is on.

I can't reproduce this with any other components from vanilla or any other mods, and I can clearly see that the Redstone Panel is definitely not outputting to the side that Redstone Link is on.

I'd recommend opening an issue on the Create issue tracker and linking back to this issue. I'll keep this open for now for additional research. A workaround would be to have something in between the panel and the Restone Link: perhaps another panel.

The screenshots below demonstrate the problem concisely.
Here, the panel is outputting redstone out the bottom. You can see that the Redstone Pen dust to the left is not picking up a signal. However both of the Redstone Links are picking it up. A Redstone Link in place of the Redstone Pen dust also picks up this signal.
![2022-12-14_17 11 51](https://user-images.githubusercontent.com/17087603/207735390-bb4ba99a-872d-4083-89c9-f57e505b10b8.png)

When the panel is outputting in any other direction but down (to the right in this case), the Redstone Links correctly pick up the signal only on the side being output.
![2022-12-14_17 12 07](https://user-images.githubusercontent.com/17087603/207735413-ac383d2c-53e1-48bf-8104-fb2b20425e62.png)

**Comment by dannydjdk** [comment] 2023-01-16 01:43
Closing this issue is it does not appear to be a Tiny Redstone bug, and therefore, there is nothing I can do about it. I'd recommend opening an issue at the Create Github and linking back to this issue.

**Closed as not planned** 2023-01-16 01:44 UTC
Labels: bug
