### ISSUE TITLE
[alpha bug] Placing panel on side of block or on top of another panel crashes game and breaks world.

### ISSUE THREAD

**Issue by SkylerMews** [dannydjdk/Tiny-Redstone#78] opened 2021-08-16 23:34 UTC
When placing a Redstone Panel on the side of a block, the game crashes. Same with placing one on top of another.

It causes the world to be unable to load. It crashes the game instantly when loading the world, basically corrupting the world.

Minecraft Version: 1.17.1
Forge Version: 37.0.34
Mod Version: 2.0.0a

Things to reproduce: 

- Place a Redstone panel on the side of a block.
- Place a Redstone panel on top of another Redstone panel.

**Comment by dannydjdk** [comment] 2021-08-17 00:15
Thanks for reporting this! This should be fixed in the next update which I expect to have posted tonight. Any worlds affected by the crash will be fixed with the update.

The actual crash I was able to reproduce occurs when you look at a panel placed in a specific orientation while the game tries to calculated the hitbox of the panel. I'm assuming this is the crash you received, but can't say for certain since your crash report isn't here. Based on your description, it seems very likely.

**Comment by SkylerMews** [comment] 2021-08-17 00:24
@dannydjdk Awesome! Thanks for the quick reply! I love this mod VERY much and has made my builds SOOO much smaller!

I can provide some crash-logs to you for debugging if you'd like, though, it seems you've already got this handled!

**Comment by dannydjdk** [comment] 2021-08-17 00:29
Should be fixed in the 1.17.1-2.0.1a update just posted.

Fortunately, I just happened to be going through issue reports and saw your issue right away. I definitely don't want to leave world breaking crash bugs out there for long.

If the update doesn't fix this for you, a crash report would definitely be helpful. Otherwise, we should be good!

Thank you! I'm glad to hear you love the mod! :)

**Comment by SkylerMews** [comment] 2021-08-19 01:07
Seems the bug had surfaced again! Sadly, this time it happened on my main world. D:
Same info as before, but here's a crashlog to go with it.
[crash-2021-08-18_19.04.10-client.txt](https://github.com/dannydjdk/Tiny-Redstone/files/7011044/crash-2021-08-18_19.04.10-client.txt)

**Comment by dannydjdk** [comment] 2021-08-19 04:07
Sorry. I missed the a block of code that also needed to change. Will be fixed in the next update.

**Comment by dannydjdk** [comment] 2021-08-19 04:27
Fixed in 1.17.1-2.0.2a. We shouldn't see this again. I failed to scan the code for other instances of the same problem, but I didn't make that mistake this time. The difference between the two crashes was that the first one occurred with empty panels, and this one occurred with panels with components. I'm guessing your game crashed after placing a component on a panel that was facing east.

**Closed by dannydjdk** 2021-08-19 04:27 UTC
Labels: bug, fixed in dev
