### ISSUE TITLE
[bug] export -> Camera freezes

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#24] opened 2021-03-20 21:49 UTC
If you export to a json file the camera gets freezed. I can move my char but i can't rotate the camera.
Cancel works fine.
After right clicking again and press cancel it works again.

**Comment by dannydjdk** [comment] 2021-03-20 21:59
If you left click with your mouse, it will unfreeze. The problem is that the OS save and open dialogs take the mouse control from Minecraft. Just clicking in Minecraft will get it back. I need to figure out how to return mouse control to the Minecraft window after the dialog closes.

**Comment by dannydjdk** [comment] 2021-03-21 15:25
Released in 1.16.5-1.5.2b

**Closed by dannydjdk** 2021-03-21 15:25 UTC
Labels: bug
