### ISSUE TITLE
[bug] crash when placing panel

### ISSUE THREAD

**Issue by imagelesskink** [dannydjdk/Tiny-Redstone#80] opened 2021-08-20 18:43 UTC
[crash-2021-08-20_14.40.11-client.txt](https://github.com/dannydjdk/Tiny-Redstone/files/7023543/crash-2021-08-20_14.40.11-client.txt)
The game crashed when I placed the redstone panel, throwing an illegal argument exception. What's worse, it saved before exiting so now it crashes whenever I load the world.

**Comment by dannydjdk** [comment] 2021-08-20 19:51
Thanks for the report. This is a duplicate of #78 and is already fixed. Upgrading to the latest version will fix it, and you'll be able to load your world again. Sorry for the inconvenience. Hopefully, it will be updated in the modpack you're playing soon.

**Closed by dannydjdk** 2021-08-20 19:51 UTC
