### ISSUE TITLE
[Feature request] 3d Redstone circuits

### ISSUE THREAD

**Issue by Fireztonez** [dannydjdk/Tiny-Redstone#11] opened 2021-03-19 02:54 UTC
I think having possibility to make redstone circuit with multiple layer can be nice and will add a lot of possibility for more complexe circuit in a compact way.

So what I imagine is:
- Having possibility Tiny Plate, where you can place 1 Tiny redstone each.
- Having possibility to bring Redstone Signal from one layer to the other with a sort of redstone cable vertical (Similar to the Redstone Impregnated Sticks from SCM)
- Like in Minecraft circuit, Tiny Redstone Torch should be hable to transmit Redstone signal on the second layer.
- In addition you can possibly add a none conductive version of the plate.

If you want to see visually an example of what you can do:
https://youtu.be/09hFVLKlBo4?t=468

You probably don't need to go with the same level of complexity than SCM let you make, but I think it can give you somes ideas for improvements.

And, if you need, codes sources of SCM have been delivered, so if this can help you in certain way, question to improved your mod, without necessarely copying the codes:
https://github.com/amadornes/SCM-Legacy

**Comment by dannydjdk** [comment] 2021-03-19 04:42
Duplicate of #8 

Thanks for the suggestions. As I mentioned in #8, I do have mixed feelings about this possibility given the significant complexity increase, both for me and for players. If I do implement this, it will probably be in a more vanilla style, since I'm trying to keep the mod as close to vanilla as possible. The idea is that, if you know how to do something with vanilla redstone, I want you to be able to use that same knowledge in Tiny Redstone. But, that may be too impractical in a 3d scenario. So, I'll definitely be considering your suggestions when I get to that point.

I'm closing this issue, because it's a duplicate, but it will be linked from the other issue. Feel free to pick up on the conversation over there.

**Closed by dannydjdk** 2021-03-19 04:42 UTC
Labels: duplicate

**Comment by Fireztonez** [comment] 2021-03-20 05:21
:o sorry I miss-read the other suggestion, and hadn't noticed it was a similar suggestion.
