### ISSUE TITLE
Wireless?

### ISSUE THREAD

**Issue by JustinTheBob** [dannydjdk/Tiny-Redstone#81] opened 2021-09-14 05:40 UTC
Would it be possible to add a wireless like device to the mod? Like having a circuit on the roof or under the house, that than teleports the signal to a light/all the lights in ur house via a wireless device? I was thinking like make a circuit that detects when it’s day/night and turns all your lights on automatically when it gets dark. Thank you!

**Comment by dannydjdk** [comment] 2021-09-14 20:58
Yes! I like this idea as an add-on mod.

My current idea is to create a ranged wireless redstone mod which has both full-sized wireless transmitters and receivers and tiny ones if Tiny Redstone is also installed. The full sized ones would have a larger range, maybe 150 blocks or something like that. The tiny ones would be around 32 blocks.

**Comment by JustinTheBob** [comment] 2021-09-14 23:22
Yesss! I’m glad you like the idea! I currently have a wireless mod installed(regular size ofc) and the way it works is you can build a big circuit anywhere and put the wireless thing down and put in a “frequency” 1-infinity I think and if u put other receivers with the same frequency they all receive that output. But it’s your mod do it how you see fit! I’ll be happy either way! Just throwing ideas at ya haha

**Comment by JustinTheBob** [comment] 2021-09-14 23:23
Maybe the receiver would be a good update to the tiny gates mod? Or a whole other add-on mod idk 😂

**Comment by JustinTheBob** [comment] 2021-09-14 23:25
Also side question, you said the little ones would have a 32 block range, that range being regular blocks not the little tile blocks? Sorry if stupid question haha

**Comment by dannydjdk** [comment] 2021-09-15 04:59
Definitely real blocks. 32 tiny blocks (4 full blocks) probably wouldn't be that useful. 😝

**Comment by JustinTheBob** [comment] 2021-09-15 13:03
Yea that’s what I was thinking 😂 glad you like the idea!

**Comment by JustinTheBob** [comment] 2021-09-16 01:11
I’m not rushing what so ever. I’m just wondering how long a code like that would take to write? ❤️

**Comment by dannydjdk** [comment] 2021-09-16 14:01
I was wondering that too. 😛
I could probably get an alpha ready for testing over the course of a weekend, but there are a couple things I need to do before that. First, I have a few changes I want to make to the base code in Tiny Redstone to improve efficiency that might change the API. After that, I need to find a weekend where I can focus on it for a good amount of time. At this point, I'd say about 2 weeks.
Once I have an alpha ready, then I'll need a few helpful players, like you, to test it out and make sure nothing is broken. 😉

**Comment by JustinTheBob** [comment] 2021-09-16 23:22
Yea I’d be down to help out and test it out! Take your time though man you’re good. If you do need help with testing just let me know I’d be glad to test it out!

**Comment by JustinTheBob** [comment] 2021-09-16 23:23
I will say I’ll be putting it on my server that me and a friend play on. Hopefully the alpha would work on there aswell! Thank you.

**Comment by dannydjdk** [comment] 2021-09-22 15:36
It's happening: https://github.com/dannydjdk/Ranged-Wireless-Redstone
I think my 2 week estimate was pretty accurate. I hope to have an alpha ready next weekend. No promises though.
Yes, the alpha should definitely work on your server.

**Comment by JustinTheBob** [comment] 2021-09-22 19:15
> It's happening: https://github.com/dannydjdk/Ranged-Wireless-Redstone
> I think my 2 week estimate was pretty accurate. I hope to have an alpha ready next weekend. No promises though.
> Yes, the alpha should definitely work on your server.

Yay! So about 1 more week and it’ll be ready for alpha testing hopefully! Once again no rush, and thank you!

**Comment by dannydjdk** [comment] 2021-09-25 14:35
It's taking Curseforge a long time to review the project, but once it does, you'll be able to find it here:
https://www.curseforge.com/minecraft/mc-mods/ranged-wireless-redstone

If you don't want to wait, I have the mod posted for you to download here:
For 1.16.5: [rangedwirelessredstone-1.16.5-0.1.1.jar](http://files.dannyandson.com/RangedWirelessRedstone/rangedwirelessredstone-1.16.5-0.1.1.jar)
For 1.17.1: [rangedwirelessredstone-1.17.1-1.0.2.jar](http://files.dannyandson.com/RangedWirelessRedstone/rangedwirelessredstone-1.17.1-1.0.2.jar)

I've done a fair amount of testing, and everything seems to be working well. But, I'm a developer, so I'm not qualified to test my own software.
I'd also be interested in hearing any feedback about features, models, recipes, etc.

Thanks!

**Comment by JustinTheBob** [comment] 2021-09-26 09:22
Just saw this, I will test it tomorrow when I wake up! Also thank god u made a 1.16.5 version, that’s the version my friend and I play on, ur amazing! Thank you!

**Comment by JustinTheBob** [comment] 2021-09-26 09:28
Miss-clicked, didn’t mean to close my bad. Just exited lmao

**Comment by JustinTheBob** [comment] 2021-09-26 18:14
Okay so i've tested it a bit! I love it! Works great! But a few things to mention(not complaints just things to help you/things I was wondering :D)
1. The tiny receiver/transmitter works like you said, 32 blocks even when going from tiny transmitter. Perfect!
2. The regular receiver/transmitter works a little different than you mentioned, 128 blocks, still perfect!(You had mentioned 150 blocks, idk if u still set it to 150 but the chunk loading is making it not work? Idk but I don't mind, 128 is ENOUGH lmao, Just mentioning just incase this was unintended)
3. Kind of of unrelated, but worth mentioning. I use the HWYLA mod(fork/port of WAILA) and the tiny wireless receiver/transmitters seems to show Channel, Signal, and power. But the regular wireless receiver/transmitters do not. Not a big deal at all, once again, just worth mentioning.
4. The tiny receiver seems to be a tiny bit buggy(see what I did there? lol), low priority bug though. More tedious than anything. When placing it, and opening the GUI to put it to lets say channel 2, clicking close to save. Once you re-open it(or look on HWYLA) it just goes back to channel 1. Than you have to re-open it and put it to the channel you want. (Just tested again before posting this, now its going back to 3? Was 1 before lol idk) Also if you take it to channel 1, then close to save, it will go back to channel 0. Than you have to re-open it and put it back to channel 1. If you take it to 1 than press the "++" and go to lets say 41, and close to save, it will go back to 11. Than you have to open it and set it back to 41 and it will save.

But none of the things I mentioned are mod/game breaking. So I'm very happy with the add-on! I love it! Thank you for taking the time to work on it. It's amazing and I love how you integrated tiny receivers/transmitters it's awesome. Let me know if there is anything certain you want me to test. Thank you have a great day!

**Comment by dannydjdk** [comment] 2021-09-27 01:46
1. :)
2. Yes, I did go with 128, just because things in Minecraft usually have limits based on bit math. It is configurable in the server config and can be as high as you want it to be. The only thing that it does not support is cross-dimensional transmittance.
3. Tiny Redstone has built-in support for The One Probe and HWYLA. So, any components built for it can also easily tap into that support. I'll need to build that into Ranged Wireless Redstone in order to add the support for the full block ones. I'll work on that soon.
4. This definitely sounds like a sync issue. I ran into a similar issue early on in development, but I swore I fixed it. I'll take another look. Definitely not a bug I'd want to keep around. Is this only happening with the receiver and not the transmitter?

By the way, in case it isn't clear, the range is set by the transmitter, not the receiver. So, any receiver, including a tiny one, can pick up a signal from a large transmitter up to 128 blocks away, and any receiver can pick up a signal from a tiny transmitter up to 32 blocks away.

Thanks for the feedback!

**Comment by dannydjdk** [comment] 2021-09-27 01:50
A note about chunk loading:
 If a transmitter chunk unloads, the game just remembers the last state of the transmitter. So, it's not necessary to keep its chunks loaded unless you need it's state to keep changing.

**Comment by JustinTheBob** [comment] 2021-09-27 04:55
2.  Okay I probably won’t mess with the 128 block limit, that’s probably enough distance for me :) thank you for letting me know for future reference!
3. Oh okay I see, hopefully that’s not a lot of extra work, doesn’t need to be added, was just mentioning it.
4. No it’s happening to both receiver and transmitter, both tiny and regular sizes. Sorry re-reading I wasn’t super clear and had a few miss-types.

Once again thank you, great and helpful add-on and if there’s anything you need me to test once I’m off work I will test it.

**Comment by JustinTheBob** [comment] 2021-09-27 04:57
> A note about chunk loading:
> If a transmitter chunk unloads, the game just remembers the last state of the transmitter. So, it's not necessary to keep its chunks loaded unless you need it's state to keep changing.

Oh okay cool! That’s worth noting! Could have an always running channel with constant power however you might wanna use it in complex circuits.

**Comment by dannydjdk** [comment] 2021-09-27 11:56
3 & 4 are already taken care of in dev. 4 was a sync issue. By default, the redstone panels only sync to client if a cell reports a change to redstone output. I think I didn't notice the bug, because I was switching between channels that had different signals. What was happening was that the channel would change successfully, but the client wouldn't know about it. So, when you opened the GUI, it would revert to the old channel, even though the server was using the new channel. Given enough time, it would update on its own. Now, it updates in real time.

If curseforge get's the project approved today, I'll post the update there. It seems to be taking an unusually long time. If not, I'll post it here again.

Also, I'm going to close this issue and open one in the Ranged Wireless Redstone GitHub. That way, I can link relevant commits to the issue more easily. A link should appear below this comment.

**Closed by dannydjdk** 2021-09-27 11:56 UTC
Labels: add-on mod
